# Generated by Django 3.2.13 on 2022-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('address', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('city', models.CharField(default='Omaha', max_length=50)),
                ('state', models.CharField(default='NE', max_length=15)),
                ('zipcode', models.CharField(default='00000', max_length=6)),
                ('email', models.EmailField(default='@gmail.com', max_length=100)),
                ('cell_phone', models.CharField(default='(402)000-0000', max_length=13)),
            ],
        ),
    ]
